/**
 * Sketch 作品 — 画像は `public/sketches`（ZIP 由来・HEIC は JPG 変換済み）。
 * 表示順: 年の新しい順、同年は Gatton → New York → Beppu、Gatton は番号順。
 */
export type SketchItem = {
  slug: string;
  title: string;
  image: string;
  year?: number;
  medium?: string;
  description?: string;
  priceNote?: string;
  detailImages?: readonly string[];
};

export const SKETCHES: readonly SketchItem[] = [
  {
    slug: "gatton",
    title: "Gatton",
    year: 2025,
    image: "/sketches/gatton.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-1",
    title: "Gatton (1)",
    year: 2025,
    image: "/sketches/gatton-1.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-2",
    title: "Gatton (2)",
    year: 2025,
    image: "/sketches/gatton-2.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-3",
    title: "Gatton (3)",
    year: 2025,
    image: "/sketches/gatton-3.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-4",
    title: "Gatton (4)",
    year: 2025,
    image: "/sketches/gatton-4.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-5",
    title: "Gatton (5)",
    year: 2025,
    image: "/sketches/gatton-5.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-6",
    title: "Gatton (6)",
    year: 2025,
    image: "/sketches/gatton-6.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-7",
    title: "Gatton (7)",
    year: 2025,
    image: "/sketches/gatton-7.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-8",
    title: "Gatton (8)",
    year: 2025,
    image: "/sketches/gatton-8.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-9",
    title: "Gatton (9)",
    year: 2025,
    image: "/sketches/gatton-9.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-10",
    title: "Gatton (10)",
    year: 2025,
    image: "/sketches/gatton-10.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-11",
    title: "Gatton (11)",
    year: 2025,
    image: "/sketches/gatton-11.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-12",
    title: "Gatton (12)",
    year: 2025,
    image: "/sketches/gatton-12.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-13",
    title: "Gatton (13)",
    year: 2025,
    image: "/sketches/gatton-13.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "gatton-14",
    title: "Gatton (14)",
    year: 2025,
    image: "/sketches/gatton-14.jpg",
    medium: "pencil on paper",
    description: "Gatton",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-1-heic-2024",
    title: "New York (1)",
    year: 2019,
    image: "/sketches/new-york-1-heic-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-1-jpg-2024",
    title: "New York (1), JPG",
    year: 2019,
    image: "/sketches/new-york-1-jpg-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-2-heic-2024",
    title: "New York (2)",
    year: 2019,
    image: "/sketches/new-york-2-heic-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-2-jpg-2024",
    title: "New York (2), JPG",
    year: 2019,
    image: "/sketches/new-york-2-jpg-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-3-heic-2024",
    title: "New York (3)",
    year: 2019,
    image: "/sketches/new-york-3-heic-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-3-jpg-2024",
    title: "New York (3), JPG",
    year: 2019,
    image: "/sketches/new-york-3-jpg-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-4-2024",
    title: "New York (4)",
    year: 2019,
    image: "/sketches/new-york-4-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-5-2024",
    title: "New York (5)",
    year: 2019,
    image: "/sketches/new-york-5-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-6-2024",
    title: "New York (6)",
    year: 2019,
    image: "/sketches/new-york-6-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-7-2024",
    title: "New York (7)",
    year: 2019,
    image: "/sketches/new-york-7-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-8-2024",
    title: "New York (8)",
    year: 2019,
    image: "/sketches/new-york-8-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-img-0907-2024",
    title: "New York — 0907",
    year: 2019,
    image: "/sketches/new-york-img-0907-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-ny-heic-2024",
    title: "New York — untitled",
    year: 2019,
    image: "/sketches/new-york-ny-heic-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "new-york-ny-jpg-2024",
    title: "New York — untitled, JPG",
    year: 2019,
    image: "/sketches/new-york-ny-jpg-2024.jpg",
    medium: "pencil on paper",
    description: "New York",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-2479-2024",
    title: "Beppu — 2479",
    year: 2024,
    image: "/sketches/beppu-2479-2024.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-5751-2024",
    title: "Beppu — 5751",
    year: 2024,
    image: "/sketches/beppu-5751-2024.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-6645-2023",
    title: "Beppu — 6645",
    year: 2023,
    image: "/sketches/beppu-6645-2023.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-6648-2023",
    title: "Beppu — 6648",
    year: 2023,
    image: "/sketches/beppu-6648-2023.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-6539-2021",
    title: "Beppu — 6539",
    year: 2021,
    image: "/sketches/beppu-6539-2021.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-0ce9-2020",
    title: "Beppu — sketch (i)",
    year: 2020,
    image: "/sketches/beppu-0ce9-2020.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-1854-2020",
    title: "Beppu — 1854",
    year: 2020,
    image: "/sketches/beppu-1854-2020.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-1855-2020",
    title: "Beppu — 1855",
    year: 2020,
    image: "/sketches/beppu-1855-2020.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-1881-2020",
    title: "Beppu — 1881",
    year: 2020,
    image: "/sketches/beppu-1881-2020.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-67d5-2020",
    title: "Beppu — sketch (ii)",
    year: 2020,
    image: "/sketches/beppu-67d5-2020.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-7225-2020",
    title: "Beppu — sketch (iii)",
    year: 2020,
    image: "/sketches/beppu-7225-2020.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
  {
    slug: "beppu-c8e7-2020",
    title: "Beppu — sketch (iv)",
    year: 2020,
    image: "/sketches/beppu-c8e7-2020.jpg",
    medium: "pencil on paper",
    description: "Beppu",
    priceNote: "Price : Ask (contact)",
  },
];
